### PR TITLE
chore: update to Quarkus 3.4.0

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Review by csviri — APPROVED** [review]
LGTM

**Comment by csviri** [comment]
Are we putting this to main with CR? What if meanwhile needs to a patch release?

**Comment by csviri** [comment]
Should not be rather just  a test branch for CRs?

**Comment by metacosm** [comment]
Yes, this isn't meant to be merged yet, just wanted to get a CI run on it.

**Pull request merged**
