### PR TITLE
feat: allow specifying operator-level namespaces to generate manifests

### LINKED ISSUE #655: Sorry I mean could a variant of generate-with-watched-namespaces work over all controllers?
Sorry I mean could a variant of generate-with-watched-namespaces work over all controllers?

_Originally posted by @shawkins in https://github.com/quarkiverse/quarkus-operator-sdk/issues/654#issuecomment-1634615274_

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #655

### CODE REVIEW

**Comment by csviri** [comment]
These features are not tested with unit tests on some level?

**Comment by metacosm** [comment]
> Shouldn't we test these features with unit tests on some level?

Yes, we should. I didn't get a chance to finish this before I left for PTO.

**Comment by shawkins** [comment]
This LGTM.  Tried the test case with quarkus.operator-sdk.generate-with-watched-namespaces=JOSDK_WATCH_CURRENT and confirmed the gernerated manifests were free of ClusterRoleBindings and namespaces.

**Pull request merged**
