### PR TITLE
Fix CRDUtils::apply by replacing serverSideApply() with get(), update() and create()

### LINKED ISSUE #659: Quarkus Operator SDK 6.1.1 breaks operator.start() in QuarkusTests
Hey folks, when updating the Quarkus Operator SDK to 6.1.1 or newer, we cannot start an injected operator in a `@QuarkusTest` anymore.

## Expected Behavior

The CRD can be applied and the operator is started (works with 6.1.0 or older).

```shell
08:40:54.393 [Test worker] INFO  i.q.o.runtime.OperatorProducer - Quarkus Java Operator SDK extension 6.1.0
  (commit: f79f1b6 on branch: f79f1b6ffcb49e453b697f37aebc27b34d45482c) built on Thu May 25 00:28:33 CEST 2023

Jul 18, 2023 8:40:54 AM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[39547] received request: POST /apis/apiextensions.k8s.io/v1/customresourcedefinitions
  HTTP/1.1 and responded: HTTP/1.1 201 OK

Jul 18, 2023 8:40:54 AM io.quarkiverse.operatorsdk.runtime.CRDUtils lambda$applyCRD$0
INFO: Applied v1 CRD named 'test-resources.donnerbart.de' from
  /home/donnerbart/IdeaProjects/operator-test/build/kubernetes/test-resources.donnerbart.de-v1.yml
```

## Actual Behavior

The CRD cannot be applied and the operator cannot be started (fails with 6.1.1 or newer).

```shell
08:41:40.530 [Test worker] INFO  i.q.o.runtime.OperatorProducer - Quarkus Java Operator SDK extension 6.1.1
  (commit: 42b0ce2 on branch: 42b0ce29cb78360650c4c409dab43bfe752b5f1a) built on Fri Jun 02 19:11:25 CEST 2023

Jul 18, 2023 8:41:40 AM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[54939] received request: PATCH
  /apis/apiextensions.k8s.io/v1/customresourcedefinitions/test-resources.donnerbart.de?fieldManager=fabric8
  HTTP/1.1 and responded: HTTP/1.1 404 Client Error
```

## Root Cause

The root cause seems to be [this change](https://github.com/quarkiverse/quarkus-operator-sdk/pull/601) in `CRDUtils.apply()` from:
```java
client.apiextensions().v1().customResourceDefinitions()
        .resource((CustomResourceDefinition) crd).createOrReplace();
```
to
```java
client.apiextensions().v1().customResourceDefinitions()
        .resource((CustomResourceDefinition) crd)
        .serverSideApply();
```

## Reproducer

* Repository: https://github.com/Donnerbart/operator-test
* Test: https://github.com/Donnerbart/operator-test/blob/main/src/test/java/de/donnerbart/operator/TestControllerTest.java
* Version properties: https://github.com/Donnerbart/operator-test/blob/main/gradle.properties#L13

When we switched our operator to Quarkus 3 and fixed the K8s client deprecations in our codebase, the `serverSideApply()` method didn't work out for us (at least not with the Kubernetes Mock Server in unit tests). We replaced everything with either `create()` or `update()` when the state/existence of a resource is known, or a `get()` and then either `update()` or `create()` when the state/existence of a resource is unknown.

Are we using the framework in a wrong way or is there a problem with `serverSideApply()` in unit tests?

### PR DESCRIPTION
**Pull request by Donnerbart**
Fixes #659

### CODE REVIEW

**Review by csviri — APPROVED** [review]
LGTM , see my comment below

**Review by csviri — COMMENTED** [review]
To be honest not sure if is this absolutely correct to have this based on `ssaBasedCreateUpdateMatchForDependentResources` since that is for completely other think.

IMO the apply of CRD could be done just by simple create / update. Since those are anwywas not managed by controllers.

@metacosm  what do you think?

**Comment by Donnerbart** [comment]
Yeah, I'm also not sure if that's really a good configuration to use. My first approach was just using `get()`, `update()` and `create()`. Just tell me what you think, I can quickly adapt the code if needed.

**Comment by csviri** [comment]
I think the CRD apply should just use get/create/update, the SSA should be removed from here.

**Comment by metacosm** [comment]
Yes, I think we can remove SSA altogether from this, this was an overzealous change on my part.

**Review by metacosm — CHANGES_REQUESTED** [review]
Please remove SSA altogether and change the commit message to follow the conventional commit format.

**Comment by Donnerbart** [comment]
The code updated. I hope I've anticipated the commit message format correctly.

**Comment by csviri** [comment]
will try to fix the workflows before merge

**Pull request merged**
