### PR TITLE
Split runtime and build time configurations

### PR DESCRIPTION
**Pull request by metacosm**
Should address java-operator-sdk/java-operator-sdk#337.

### CODE REVIEW

**Comment by metacosm** [comment]
Can you give this a try, @cortex93?

**Comment by cortex93** [comment]
Did the job. Thank you

**Comment by metacosm** [comment]
@cortex93 Thanks for checking. Glad to hear it worked as expected.

**Comment by cortex93** [comment]
Would you mind make a release with this MR ?

**Pull request merged**
