### PR TITLE
fix: remove duplicated and wrong env variable

### PR DESCRIPTION
**Pull request by metacosm**
- **fix: properly log when helm generation is disabled**
- **fix: do not modify deployment as it is live and reused elsewhere**

### CODE REVIEW

**Review by csviri — APPROVED** [review]
LGTM

**Comment by jcechace** [comment]
@metacosm LGTM. I will attempt to build QOSDK from sources and  try it against real source. 

If everything works, is there a chance for you to cut a release containing this fix later today / tomorrow?

**Comment by metacosm** [comment]
> @metacosm LGTM. I will attempt to build QOSDK from sources and try it against real source.
> 
> If everything works, is there a chance for you to cut a release containing this fix later today / tomorrow?

That's the plan.

**Comment by jcechace** [comment]
@metacosm Just tested the fix and all seems to be in order. Thanks for the quick fix!

**Pull request merged**
