### PR TITLE
wip: attempt at reusing configuration processing from JOSDK

### PR DESCRIPTION
**Pull request by metacosm**
- chore: remove bundle generation from IT since we're not testing this
- doc: add deactivated property to point out how to see generated code
- wip: attempt at reusing configuration processing from JOSDK

### CODE REVIEW

**Comment by metacosm** [comment]
How to work with this PR:
- Checkout and build locally: https://github.com/java-operator-sdk/java-operator-sdk/pull/1582
- Checkout and build locally this PR
- Run: `mvn clean install`, the tests in the `integration-tests` module should fail with:
  ```java
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OperatorSDKResourceTest.dependentAnnotationsShouldAppearInConfiguration:129 2 expectations failed.
JSON path dependents.dependentConfig.labelSelector doesn't match.
Expected: a collection containing "environment=production,foo=bar"
  Actual: <[]>

JSON path dependents.dependentConfig.onAddFilter doesn't match.
Expected: a collection containing "io.quarkiverse.operatorsdk.it.CRUDDependentResource.TestOnAddFilter"
  Actual: <[]>
```

**Comment by geoand** [comment]
I'll have a look (likely tomorrow)

**Comment by geoand** [comment]
I am getting:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project quarkus-operator-sdk-deployment: Compilation failure: Compilation failure: 
[ERROR] /home/gandrian/projects/redhat/quarkus-operator-sdk/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java:[16,52] cannot find symbol
[ERROR]   symbol:   class Instantiator
[ERROR]   location: class io.javaoperatorsdk.operator.api.config.Utils
[ERROR] /home/gandrian/projects/redhat/quarkus-operator-sdk/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java:[128,62] cannot find symbol
[ERROR]   symbol:   class Instantiator
[ERROR]   location: class io.quarkiverse.operatorsdk.deployment.QuarkusControllerConfigurationBuilder
[ERROR] -> [Help 1]
```

**Comment by metacosm** [comment]
> I am getting:
> 
> ```
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project quarkus-operator-sdk-deployment: Compilation failure: Compilation failure: 
> [ERROR] /home/gandrian/projects/redhat/quarkus-operator-sdk/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java:[16,52] cannot find symbol
> [ERROR]   symbol:   class Instantiator
> [ERROR]   location: class io.javaoperatorsdk.operator.api.config.Utils
> [ERROR] /home/gandrian/projects/redhat/quarkus-operator-sdk/core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java:[128,62] cannot find symbol
> [ERROR]   symbol:   class Instantiator
> [ERROR]   location: class io.quarkiverse.operatorsdk.deployment.QuarkusControllerConfigurationBuilder
> [ERROR] -> [Help 1]
> ```

Sorry, I hadn't pushed the latest version of the JOSDK branch… Should be fixed now.

**Comment by metacosm** [comment]
Out of date. Will re-open a new one if needed in the future.

**Pull request closed without merging**
